### ISSUE TITLE
Review request for kaban board

### ISSUE THREAD

**Issue by Meltrust** [Meltrust/Space-Travelers-Hub#25]
# Kanban Board review request for 2 team members group.

## In this milestone we:

- Created a kanban board with equal score activities according to the requirements of the project.
- Members in team: 2

Link:
https://github.com/Meltrust/Space-Travelers-Hub/projects/1

**Comment by fernandorpm** [comment]
# :heavy_check_mark: Pull Request Approved! :heavy_check_mark:
WOW WHAT IS THIS PERFECTION??????? WERE HUMANS SUPPOSED TO BEHOLD SUCH POWER????

Congratulations on your hard work! Please remember to merge the project and don't forget that you're awesome! :heart:

<img src="https://i.imgur.com/gOjmIlL.gif" width="300px" />

- You have done a wonderful job on this project! To highlight:
  - you have demonstrated great skills in following the template :heavy_check_mark: 
  - you have paid attention to almost all of the details :heavy_check_mark: 

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Just keep in mind that Microverse has a standard for the project requirements, to guarantee that you will be able to become a great developer, and both you and I have to follow them!

___
Cheers and Happy Coding! :heart:

> *As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).*
